monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        mail:
            type: fingers_crossed
            action_level: error
            handler: duplicado

        duplicado:
            type: deduplication
            handler: swift

        swift:
            type: swift_mailer
            from_email: 'error@gmail.com'
            to_email: 'envioson@gmail.com'
            subject: 'Ocorreu algum error :  %%messge%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html

        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
