<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEyF52Pe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEyF52Pe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEyF52Pe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEyF52Pe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEyF52Pe\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'EyF52Pe',
    'container.build_id' => 'd289172e',
    'container.build_time' => 1549995516,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEyF52Pe');
