<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSA8G69L\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSA8G69L/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSA8G69L.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSA8G69L\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSA8G69L\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'SA8G69L',
    'container.build_id' => '11ae0316',
    'container.build_time' => 1549994221,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSA8G69L');
