<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP2x8GWo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP2x8GWo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP2x8GWo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP2x8GWo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP2x8GWo\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'P2x8GWo',
    'container.build_id' => '24cbce86',
    'container.build_time' => 1550057061,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerP2x8GWo');
